### ISSUE TITLE
Unable to use published module

### ISSUE THREAD

**Issue by loopmode** [wwwtyro/dis-gui#1]
Hi there

Pretty cool project!! However, several issues make it unusable out-of-the box.

1) The version published on npm is not transpiled, you quickly run into unexpected `import` errors - typically one excludes the node_modules from transpiling in a real-world project
2) Trying to `npm run build` the downloaded version inside node_modules fails - because of some gh-pages file not found error

So I went ahead, made a fork and published it under my namespace. I changed the build setup from browserify to babel and already fixed several issues.
I'm really happy with the version I am using now.

If you'd like to revive the project, we can surely merge back via PR - otherwise I'd be happy if you give me full access here so I can maintain the project and deprecate my fork.

https://www.npmjs.com/package/@loopmode/dis-gui
https://github.com/loopmode/dis-gui
https://github.com/loopmode/dis-gui/blob/master/CHANGELOG.md

**Comment by wwwtyro** [comment]
@loopmode That would be awesome. I've invited you to collaborate. Go ahead and take over.

**Comment by wwwtyro** [comment]
@loopmode I've also added you as a collaborator to the npm repo.

**Comment by loopmode** [comment]
great! thank you
