### ISSUE TITLE
Select doesn't update if something else changes the state

### ISSUE THREAD

**Issue by pailhead** [wwwtyro/dis-gui#3]
I have something like this:
```
<dg.Select
                        label="normal map"
                        options={this.props.normalMaps}
                        value={this.props.normalMap}
                        onChange={this.props.onNormalMapChange}
                    />

                    <dg.Button
                        label="Next map"
                        onClick={this.props.onNextNormalMap}
                    />
```

`this.props.normalMap` changes as result of the `Button`'s onClick, but the select element does not.

**Comment by pailhead** [comment]
Will give it a shot.

**Comment by pailhead** [comment]
I couldn't actually get it to work, changing it results in the demo only being able to go to Fractal once, and never back to Smooth.

**Comment by loopmode** [comment]
ah crap. just fired up a fresh create-react-app to test and fix this... we'll have to rewrite `context` usage to support react 16 :)

Trying to reproduce and fix, expect an update soon

**Comment by pailhead** [comment]
Actually it worked, i think it's something with the demo that i found confusing, the props never got triggered. If i change it to state, it works.

**Comment by pailhead** [comment]
I can make a PR.

**Comment by loopmode** [comment]
Not sure what demo we are talking about.. Could you clarify / send link?

**Comment by pailhead** [comment]
`example/demo.jsx` the the handlers in `example/main.js` don't trigger rerenders.
